### DISCUSSION TITLE
persist database/state between restarts

### DISCUSSION THREAD

**Discussion by hozza** [AlexGustafsson/cupdate#275] [Q&A] [answered]
Is it sensible to persist the databases between container restarts? I'm assuming this would be handy to avoid using up registry rate limits if the container is restarted often.

Looking through the config maybe something like this in a compose would work (volume mounts) - or would this upset the architecture/design any anyway? My setup is just one container, no k8 or anything like that.

```yaml
version: "3.8"
services:
  cupdate:
    container_name: cupdate
    image: ghcr.io/alexgustafsson/cupdate:0.20.0
    ports:
      - 8080:8080
    environment:
      CUPDATE_CACHE_PATH: /var/run/cachev1.boltdb
      CUPDATE_DB_PATH: /var/run/dbv1.sqlite
      CUPDATE_DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./cachev1.boltdb:/var/run/cachev1.boltdb
      - ./dbv1.sqlite:/var/run/dbv1.sqlite
      - - target: /tmp
        type: tmpfs

```

**Comment by AlexGustafsson** [comment]
Persisting the state is a great way to help speed things up. Cupdate doesn't rely on it, but it's generally advisable. Your config looks correct and should persist data in `./dbv1.sqlite` and cache in `./cachev1.boltdb`. 

I can't remember why I left that out of the documented compose file, maybe it was just to provide a minimal example and let users modify it to taste.

**Reply by hozza** [reply]
Since the files are created by the container rather than being created by hand before. I had to use the long form bind mount to ensure the file names were not created as directories (a docker quirk).

I ran it fine, once, but on a container restart it immediately corrupted the database. Could you test this on your end to see if I'm doing anything wrong?

**Reply by AlexGustafsson** [reply]
Well, there is one thing that could cause this behaviour. I've turned on WAL for SQLite, so there might actually be additional files (.wal) next to the SQLite file that can contain data that's not yet been committed to the main file. Maybe it would make more sense to mount an entire directory like "data" and make sure Cupdate stores its data inside of that directory. Could you try that and see if you get some additional files on your host? Do you see any general / opinionated issues with mounting a directory as opposed to single files? I'd happily take feedback on that.

**Reply by hozza** [reply]
> Well, there is one thing that could cause this behaviour. I've turned on WAL for SQLite, so there might actually be additional files (.wal) next to the SQLite file that can contain data that's not yet been committed to the main file. Maybe it would make more sense to mount an entire directory like "data" and make sure Cupdate stores its data inside of that directory. Could you try that and see if you get some additional files on your host? 

Ah I see, is it wise to mount the whole `/var/run/`> or should I tweak the ENV paths and then mount a full directory like `/var/run/data/`?

> Do you see any general / opinionated issues with mounting a directory as opposed to single files? I'd happily take feedback on that.

Yes, it's almost always "mount a config directory" over mounting files directly. Especially due to [this docker quirk](https://www.reddit.com/r/docker/comments/uixqpt/comment/i7h129s/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button).

Having a "data" directory mount in the examples would make updating/migration easier, should you add any other files, peoples compose files would not need to mount more individual files.

**Comment by hozza** [comment, marked as answer]
I changed it to use a "data" folder for mount, and it seems to be working well.

```yml
version: "3.8"
services:
  cupdate:
    container_name: cupdate
    image: ghcr.io/alexgustafsson/cupdate:0.20.0
    # ports:
    #   - 127.0.0.1:58080:8080 # caddy now
    environment:
      CUPDATE_CACHE_PATH: /var/run/data/cachev1.boltdb
      CUPDATE_DB_PATH: /var/run/data/dbv1.sqlite
      CUPDATE_DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
      - /mnt/storage/containers/cupdate/data/:/var/run/data/
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - target: /tmp
        type: tmpfs

```

Change "/mnt/storage/containers/cupdate/data/" to wherever you want your data stored, maybe just "./data/".

> Could you try that and see if you get some additional files on your host?

Yes I'm seeing a couple of other files. `dbv1.sqlite-shm` and `dbv1.sqlite-wal`

![Screenshot from 2025-05-27 14-24-03](https://github.com/user-attachments/assets/d700476e-a7f0-4bc7-9b82-2e9324d1a314)
