### ISSUE TITLE
persist database/state between restarts

### ISSUE THREAD

**Issue by hozza** [AlexGustafsson/cupdate#269]
Is it sensible to persist the databases between container restarts? I'm assuming this would be handy to avoid using up registry rate limits if the container is restarted often.

Looking through the config maybe something like this in a compose would work (volume mounts) - or would this upset the architecture/design any anyway? My setup is just one container, no k8 or anything like that.

```yaml
version: "3.8"
services:
  cupdate:
    container_name: cupdate
    image: ghcr.io/alexgustafsson/cupdate:0.20.0
    ports:
      - 8080:8080
    environment:
      CUPDATE_CACHE_PATH: /var/run/cachev1.boltdb
      CUPDATE_DB_PATH: /var/run/dbv1.sqlite
      CUPDATE_DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./cachev1.boltdb:/var/run/cachev1.boltdb
      - ./dbv1.sqlite:/var/run/dbv1.sqlite
      - - target: /tmp
        type: tmpfs

```
