### ISSUE TITLE
Feature Request: Create a dedicated API to return Summary

### ISSUE THREAD

**Issue by emouawad** [AlexGustafsson/cupdate#64]
### User stories

- As a user i want to consume a simple API call to get the summary
- Useful to be used with other integrations like status pages (https://gethomepage.dev/widgets/services/customapi/)
- Badges can be also created with such API

### Feature description

Currently api/v1/images returns summary + all the images status, this is not optimal and not needed to get only the overall status frequently.
I intend to use this with gethomepage.dev which will frequently call it.
Already created a POC from api/v1/images but looking to optimize it.

![image](https://github.com/user-attachments/assets/73d4f0ec-ad5e-42b9-b7e4-d2981971d931)

Thanks for this lovely project - been looking for something as good as this! :heart

**Comment by AlexGustafsson** [comment]
Thank you for the kind words!

I've been looking at getting something like this working with [Homer](https://github.com/bastienwirtz/homer) as well. It would be great if we can come up with one solution that works in both cases.

**Comment by AlexGustafsson** [comment]
Oh, and could you share how you got it working with homepage? There might be others looking for the same thing.

**Comment by emouawad** [comment]
> * https://gethomepage.dev/widgets/services/customapi/

Already mentioned: https://gethomepage.dev/widgets/services/customapi/

Using traefik annotations:

```yaml
    gethomepage.dev/widget.type: customapi
    gethomepage.dev/widget.url: http://cupdate.cupdate/api/v1/images
    gethomepage.dev/widget.method: GET
    gethomepage.dev/widget.mappings.0.label: "outdated"
    gethomepage.dev/widget.mappings.0.field.summary: "outdated"
    gethomepage.dev/widget.mappings.1.label: "images"
    gethomepage.dev/widget.mappings.1.field.summary: "images"
    gethomepage.dev/widget.mappings.2.label: "vulnerable"
    gethomepage.dev/widget.mappings.2.field.summary: "vulnerable"
    gethomepage.dev/widget.mappings.3.label: "processing"
    gethomepage.dev/widget.mappings.3.field.summary: "processing"
```
